name: 'Prepare MacOS system'
description: 'Prepare system for building R'
inputs:
  fortran:
    description: 'Install Fortran compiler'
    default: true
  tinytex:
    description: 'Install TinyTex'
    default: true
  xquartz:
    description: 'Install xQuartz'
    default: false

runs:
  using: "composite"
  steps:
    - name: Set SDK to match CRAN
      shell: bash
      run: |
        if [ "$(uname -m)" = "x86_64" ]; then
          sudo xcode-select -s /Applications/Xcode_16.2.app || true
          echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV
        else
          sudo xcode-select -s /Applications/Xcode_26.0.app || true
          echo "MACOSX_DEPLOYMENT_TARGET=14.0" >> $GITHUB_ENV
        fi
        echo "xcode is set: $(xcode-select --print-path)"
        echo "using SDK: $(xcrun --show-sdk-version)" || true

    - name: Remove homebrew packages
      shell: bash
      run: brew unlink $(brew list --formula) || true

    - name: Install CRAN fortran build
      if: inputs.fortran
      shell: bash
      run: |
        curl --retry 3 --fail-with-body -sSLO https://github.com/R-macos/gcc-14-branch/releases/download/gcc-14.2-darwin-r2.1/gfortran-14.2-universal.pkg
        sudo installer -pkg "gfortran-14.2-universal.pkg" -target /
        rm -f gfortran-14.2-universal.pkg
        echo "/opt/gfortran/bin" >> $GITHUB_PATH
        echo "FC=/opt/gfortran/bin/gfortran" >> $GITHUB_ENV

    - name: Download CRAN system libraries
      shell: bash
      run: |
        sudo mkdir -p /opt
        sudo chown $USER /opt
        curl --retry 3 --fail-with-body -sSL https://github.com/r-universe-org/macos-libs/releases/download/2025-12-13/cranlibs-everything.tar.xz -o libs.tar.xz
        sudo tar -xf libs.tar.xz -C / opt
        rm -f libs.tar.xz
        echo "/opt/R/$(uname -m)/bin" >> $GITHUB_PATH
        echo "PKG_CONFIG_PATH=/opt/R/$(uname -m)/lib/pkgconfig:/opt/R/$(uname -m)/share/pkgconfig" >> $GITHUB_ENV

    - name: Install TinyTex
      if: ${{ inputs.tinytex }}
      uses: r-lib/actions/setup-tinytex@v2
      env:
        TINYTEX_INSTALLER: TinyTeX

    - name: Install additional LaTeX packages
      if: ${{ inputs.tinytex }}
      run: |
        tlmgr update --self
        tlmgr install texinfo
        tlmgr list --only-installed
        echo "$HOME/Library/TinyTeX/bin/universal-darwin" >> $GITHUB_PATH
      shell: bash

    - shell: bash
      if: inputs.xquartz
      run: |
        if [ -d "/opt/X11/lib" ]; then
          echo "/opt/X11/lib exists. Skipping xQuartz installation"
        else
          echo "::group::Installing XQuartz"
          echo "Downloading XQuartz..."
          curl --retry 3 --fail-with-body -LO https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.5/XQuartz-2.8.5.pkg
          sudo installer -pkg "XQuartz-2.8.5.pkg" -target /
          rm -f XQuartz-2.8.5.pkg
          echo "Done installing XQuartz!"
          echo "::endgroup::"
        fi
